#超时重试
ribbon:
    ReadTimeout: 60000 # 单位ms
    ConnectTimeout: 60000 # 单位ms
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1

#熔断回调超时
hystrix:
   command:
       default:
          execution:
             timeout:
                  enabled: true
             isolation:
                 thread:
                    timeoutInMilliseconds: 180000 # 默认是1秒

