spring:
   profiles:
      active: ${active:dev}
   application:
      name: springCloud.zuul

server:
   port: 800
#   context-path: /zuul

#配置注册中心的参数
eureka:
   client:
      serviceUrl:
            defaultZone: ${registry.url}
      registry-fetch-interval-seconds: 5 # 拉取服务注册信息间隔时间 (默认为30秒)
   instance:
          lease-expiration-duration-in-seconds: 60  # 注册中心超过这个时间没收到心跳，会视为无效节点(默认为90秒)
          lease-renewal-interval-in-seconds: 30  # 发送心跳间隔时间（默认30秒）
          preferIpAddress: true
          instanceId: ${spring.cloud.client.ip-address}:${server.port}
      

zuul:
  add-host-header: true #webui重定向  请求头host显示为网关的（eg:localhost:9090）而非webui的
  ignoredServices: '*' #禁用服务名路游
  sensitive-headers:   #传递头信息
  retryable: true  #负载均衡时，路游的服务重启时，可通过重试到其他相同服务
#  host:
#     socket-timeout-millis: 60000
#     connect-timeout-millis: 60000
#zuul中网路由一定要在这里配置，不然发访问不到微服务，getway不配置也可以访问
  routes:
    webui:
      path: /webui/**
      serviceId: webui
    webapi:
      path: /webapi/**
      serviceId: webapi
