spring:
   application:
       name: webui
   thymeleaf:
           prefix: classpath:/templates/
           suffix: .html
           mode: LEGACYHTML5
           encoding: UTF-8
           content-type: text/html
           cache: false

server:
   port: 805  #微服务webui的端口

eureka:
    client:
       serviceUrl:
            defaultZone: ${registry.url}  #从配置中心读取配置
       registry-fetch-interval-seconds: 5 # 拉取服务注册信息间隔时间 (默认为30秒)
    instance:
          lease-expiration-duration-in-seconds: 60
          lease-renewal-interval-in-seconds: 30
          preferIpAddress: true
          instanceId: ${spring.cloud.client.ip-address}:${server.port}


